version: '3'

services:
  metasploitable:
    build: ./metasploitable
    image: metasploitable
    container_name: metasploitable
    tty: true
    networks:
      channel:
        ipv4_address: 10.0.0.2
  
  metasploit:
    build: ./metasploit
    image: metasploit
    container_name: metasploit
    tty: true
    networks:
      channel:
        ipv4_address: 10.0.0.3
            
  openvas:
      image: mikesplain/openvas
      container_name: openvas
      ports:
        - "443:443"
      networks:
        channel:
          ipv4_address: 10.0.0.4

networks:
  channel:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
